version: '3.8'
services:
  service-discovery:
    image: service-discovery
    restart: always
    container_name: service-discovery
    ports:
      - '8761:8761'
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    networks:
      - 'dockernetflix-network'
  public-service:
    image: public-service
    restart: always
    container_name: public-service
    ports:
      - '8080:8080'
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
    depends_on:
      - service-discovery
    links:
      - service-discovery
    build:
      context: ./public-service
      dockerfile: Dockerfile
    networks:
      - 'dockernetflix-network'
  subscriptionservice:
    image: subscriptionservice
    restart: always
    container_name: subscriptionservice
    ports:
      - '8081:8081'
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
    depends_on:
      - service-discovery
    links:
      - service-discovery
    build:
      context: ./subscriptionService
      dockerfile: Dockerfile
    networks:
      - 'dockernetflix-network'
  emailservice:
    image: emailservice
    restart: always
    container_name: emailservice
    ports:
      - '8082:8082'
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
    depends_on:
      - service-discovery
    links:
      - service-discovery
    build:
      context: ./emailservice
      dockerfile: Dockerfile
    networks:
      - 'dockernetflix-network'
networks:
  dockernetflix-network: #necesitamos crear en una red para alojar los servicios en ella y que pu