version: '3.8'
services:
  service-discovery:
    image: service-discovery
    restart: always
    container_name: service-discovery
    ports:
      - '8761:8761'
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    networks:
      - 'dockernetflix-network'
  public-service:
    image: public-service
    restart: always
    container_name: public-service
    ports:
      - '8080:8080'
    build:
      context: ./public-service
      dockerfile: Dockerfile
    networks:
      - 'dockernetflix-network'
  subscriptionService:
    image: subscriptionservice
    restart: always
    container_name: subscriptionservice
    build:
      context: ./subscriptionService
      dockerfile: Dockerfile
    networks:
      - 'dockernetflix-network'
  emailService:
    image: emailservice
    restart: always
    container_name: emailservice
    build:
      context: ./emailService
      dockerfile: Dockerfile
    networks:
      - 'dockernetflix-network'
networks:
  dockernetflix-network: #necesitamos crear en una red para alojar los servicios en ella y que pu